// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://auqlqxmgfxaueiainyrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1cWxxeG1nZnhhdWVpYWlueXJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MjA4MjksImV4cCI6MjA2ODA5NjgyOX0.uoAbno60NsfDwPJHFQeWEkiQfZZG2yywTTPF-SP4r9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});