// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsqrbhbompqssogjriya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzcXJiaGJvbXBxc3NvZ2pyaXlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0OTM2NzMsImV4cCI6MjA1NDA2OTY3M30.ygFeYe3g48-cTHawUt22U0xiFRIo8UemPGKg0t_0A94";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);